### ISSUE TITLE
乱数の生成方法

### ISSUE THREAD

**Issue by mat-der-D** [aidoyuzuna/firefish-lucycolor-bot#1]
今の実装だと、乱数が日付と独立に生成されていて、以下の理由で直観的でない気がする。
- 同じ日付で占っても、占う度にラッキーカラーが変わる。
- 日付に依存しない乱数なので「その日を占ってる」感がない

(どっちも「気分の問題」「そういう仕様です」とするのならそれでもいいかという内容)

日付に依存しつつ、なんらかの意味で乱数を発生させる方法はいろいろありそうだけど、例えば乱数のシード値を日付から一通りに定まる数値に設定する方法がよさそう。
(シード値とは名前の通り乱数の"タネ"になる数値のこと。これが一定なら乱数の出方も同じになる。python の random はたぶんデフォルトでは内部的に毎回違うシード値になる工夫をしてるはず。)

例えば
```
seed_num = int(month) * 32 + int(day)
random.seed(seed_num)
```
してから random.sample するとか…？

**Comment by aidoyuzuna** [comment]
乱数シード固定実装しました。

> 同じ日付で占っても、占う度にラッキーカラーが変わる。
今回の最終目的であるノート投稿だと乱数固定の恩恵が少ないですが、もし今後おみくじプログラムなど作った場合に支障が出てきそうなので、一度勉強の一環で入れてみました。

**Comment by mat-der-D** [comment]
いいと思います！！解決したので close します。
