### ISSUE TITLE
datetime.date の活用

### ISSUE THREAD

**Issue by mat-der-D** [aidoyuzuna/firefish-lucycolor-bot#2]
Python 標準のモジュールで datetime モジュールというのがあり、その中に date 型というものがある。今回のケースではあまり重要でないかもしれないが、以下の点で datetime.date 型を挟んだほうが得策だと思う:
- 入力値の validation を行える (変な入力だと date 型の変数を作る際にエラーになってくれる)
- 出力の形式をある程度コントロールしやすい (strftime メソッドや format を使った表記等)
- コアのロジックと入力値のハンドリングのロジックを分離する際に、その間のインターフェースとして使いやすい
- 他の占い関連の何かを作るときに知識が役立ちそう

参考:
strftime 等
https://note.nkmk.me/python-datetime-usage/
format
https://atmarkit.itmedia.co.jp/ait/articles/2111/09/news015.html

**Comment by aidoyuzuna** [comment]
datetime.date 方式で実装してみました。
前回のプログラムは「旧TwitterのBOTに登録するために、1日ずつ出力→コピー」でやっていましたが、今後Firefishのノート投稿する際は当日もしくは次の日に投稿する形でもいいかなと思い、datetimeモジュールを使いつつ仕様を変更しました。

（純粋にinputからdatetimeに変換する技量もなかっただけとも言いますが……）

**Comment by mat-der-D** [comment]
とても良いと思います！！解決したので close します。
